import crypto from 'crypto';
import config from './lib/config';

const hashApiKey = () => crypto.createHmac('sha256', config('PUBLIC_WT_URL'))
      .update(config('EXTENSION_SECRET'))
      .digest('hex');

const template = ({username}) => `
// This rule has been automatically generated by the Auth0 Account Link Extension
// Updated by ${username}, ${new Date().toISOString()}

function(user, context, callback) {

}
`;

export default template;
